### ISSUE TITLE
Improve Readme.md

### ISSUE THREAD

**Issue by selamanse** [selamanse/playits#1]
I'd like some help to improve my readme file within following aspects:
- is it understandable?
- code snippets?
- other things that need to be explained
- typos

**Comment by pranayyelugam** [comment]
I would like to do this

**Comment by selamanse** [comment]
Yes, note that some things have been done: #2

**Comment by selamanse** [comment]
Thanks to everyone for contributing. I think this issue can be closed for now as readme seems to be nicely improved.
